### PR TITLE
Update condition.rmd

### PR DESCRIPTION
**Pull request by Laurels1**
Added additional details of preliminary results relating condition to environmental indices and recruitment implications.

### CODE REVIEW

**Comment by andybeet** [comment]
Thanks Laurel. I'll need to add this to the github submission issue since we are trying to avoid direct rmd edits at this time. this is not a problem though. thanks

**Comment by Laurels1** [comment]
Ah, sorry about that. Thanks Andy! Let me know if I should submit the GitHub issue.Sent from my iPhoneOn Feb 7, 2024, at 3:50 PM, Andy ***@***.***> wrote:﻿
Thanks Laurel. I'll need to add this to the github submission issue since we are trying to avoid direct rmd edits at this time. this is not a problem though. thanks

**Comment by andybeet** [comment]
no problem. updates have been made and will be visible upon next catalog build.
Caveat: Text can not be interspersed between images so all images follow text.

**Comment by Laurels1** [comment]
Great, thanks!Sent from my iPhoneOn Feb 7, 2024, at 5:59 PM, Andy ***@***.***> wrote:﻿
no problem. updates have been made and will be visible upon next catalog build.
Caveat: Text can not be interspersed between images so all images follow text.

**Pull request closed without merging**
