### PR TITLE
Full implementation and catalog rebuild with new dataset names

### LINKED ISSUE #134: [Bug Report]: Some image files are not appearing on catalog pages
### Describe the bug

Some image files included in github issues are not showing up online. See [mesozooplankton page for example](https://github.com/NOAA-EDAB/catalog/issues/79)

### Describe the situation

missing images

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by BBeltz1**
Much of the renaming of datasets occurred in our online issues. Those are complete but won't appear here.

Page names have been changed in the `bookdown.yml` file to ensure renamed pages propagate online. Page links will change according to new dataset names. Links to associated tech doc pages are also changed. These will not work until tech doc is pushed online as well.

Issue template dropdowns have been adjusted with name replacements as well.

Catalog has been fully rebuilt to incorporate these name changes. Most pages shown below have not actually been changed.

This pull request needs 1 reviewer to verify that the book builds locally.

Closes #134

### CODE REVIEW

**Review by sgaichas — CHANGES_REQUESTED** [review]
Two pages are missing visualizations
* Bottom temperature in situ
* Sea-surface Temperature anomaly

**Comment by BBeltz1** [comment]
Thanks Sarah, I'll take a look

**Comment by andybeet** [comment]
This is happening because of the addition of the argument `n` in some of the functions. The `make_rmd` function has `if` statements based on the number of function arguments. Will need to rework this function. May be a good idea to sketch out the flow of the function and think about a little rewrite

**Comment by andybeet** [comment]
@BBeltz1 @sgaichas So i modified the [`make_rmd`](https://github.com/NOAA-EDAB/catalog/blob/andy_update_makermd/R/make_rmd.R) function. This fix adds `n=10` to the plots that were designated to have short term trend estimated. It's a little hacky but was quick. @BBeltz1 is reviewing it now. If this works we'll pull it into this Branch for all to review

**Comment by BBeltz1** [comment]
@andybeet this is building correctly on my end now. thanks for the reminder about `arfit`

**Comment by BBeltz1** [comment]
The requested changes have been made and are ready for review.

**Comment by andybeet** [comment]
@sgaichas This builds for me. I see the figures for the two pages you referenced above. I also see the short term trend applied to some of the datasets. I think we might be good to go!

**Review by sgaichas — APPROVED** [review]
Yes, this looks good now. Thanks!

**Review by andybeet — APPROVED** [review]
looks good

**Pull request merged**
