### PR TITLE
Operation phoenix initiation

### PR DESCRIPTION
**Pull request by andybeet**
### GitHub issues

* by pass dev for now. need to sort that out
* code in `R` folder to process GitHub Issues
* code in `R` folder to create rmds from GitHub issues
* all new rmds for the catalog that use ecodata plot functions (`chapters` folder)
* added "header" rmds to split sections (`chapters/sectionHeaders`)

### Reorg

* Moved older/redundant? scripts into `oldscripts` folder

## New Look

* reowrked `_bookdown.yml` and `_output.yml`
* Stripped `index.rmd` of old content
* uses bookdown bs4_book theme for website

### CODE REVIEW

**Comment by andybeet** [comment]
@BBeltz1 once pulled i am sure the deployment to gh-pages will fail. i will fix these directly on the main/master branch

**Comment by BBeltz1** [comment]
@andybeet tried to build the book (`bookdown::render_book()`). Rendering failed via the following error:
 
image

**Comment by andybeet** [comment]
Yeah ok. Can you comment out a line in the bookdown.yml found in the root directory? The line that says chapters/productivity_anomaly.rmd then push. Thank. I'll check later tonight

**Comment by BBeltz1** [comment]
Yeah I'll do that, check the rendered book and push to the branch.

**Comment by BBeltz1** [comment]
Failed on bottom_temp_comp as well:
image

**Comment by andybeet** [comment]
Yeah, that might be a local issue. If you pull your ecodata branch and build it. Then restart rstudio and open catalog then build book should pass this point

**Comment by andybeet** [comment]
And the workflow above  fails because it needs changes from ecodata in master. I'll sort the workflow out later tonight

**Review by BBeltz1 — APPROVED** [review]
looks good

**Pull request merged**
